### ISSUE TITLE
Export Failure

### ISSUE THREAD

**Issue by MakD** [dbeley/youtube_extract#3]
f"{args.export_format} format not supported as export format. Exiting.",
                                                                          ^
SyntaxError: invalid syntax
![Screenshot (100)](https://user-images.githubusercontent.com/8217200/77829075-9da8f800-7145-11ea-990b-a933633611a9.png)

**Comment by dbeley** [comment]
Hello sorry for the error, it was a problem with python version inferior to 3.7, where some syntax isn't supported yet.

I reverted to an older equivalent syntax and hopefully it's working now.

Can you try updating and telling me if it's fixed ? Thanks in advance.

**Comment by MakD** [comment]
No Help. I updated to python 3.7.0
![Screenshot (110)](https://user-images.githubusercontent.com/8217200/77966594-f7a1ed00-7300-11ea-82c7-1042e01b4afa.png)

**Comment by dbeley** [comment]
Hi sorry that was another error in the code where library imports wasn't properly made when running the script with `python youtube_extract`. It should be fixed now, please retry and let me know!

**Comment by MakD** [comment]
PS C:\Users\maxdi\OneDrive\Desktop\New folder (2)\youtube_extract-master> python youtube_extract https://www.youtube.com/channel/UC6ZQ-SuhvQAeQIR5tHJGGmQ -e xlsx
Traceback (most recent call last):
  File "C:\Users\maxdi\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\maxdi\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "youtube_extract\__main__.py", line 7, in <module>
    from youtube_extract import ydl_utils
ModuleNotFoundError: No module named 'youtube_extract'

**Comment by dbeley** [comment]
That's very strange it's working on my end.

Can you try with forcing the use of module import with this command ?
`python -m youtube_extract CHANNEL_URL`

**Comment by MakD** [comment]
![Screenshot (125)](https://user-images.githubusercontent.com/8217200/78052956-79dfef00-739d-11ea-88c8-bf102287401e.png)
Facing Strange errors :( don't know why. can you try with the url given in my previous post please?

**Comment by dbeley** [comment]
Hello! It seems you doesn't have the dependencies installed and that python 3.7 isn't properly using it's own `pip` to install the dependencies.

To launch the program you can't just have python, you need the youtube_dl, pandas and openpyxl dependencies.

It also seems that windows is conflicting Python 3.5 and Python 3.7, because when you launch the `python` command he's launching python 3.7, and when you try to run `pip` it is searching in the python 3.5 folder.

You should try to properly uninstall python 3.5, and maybe reinstall python 3.7. I don't know well windows but there might be a "Python command prompt" program that is installed with Python, you should use that to run commands (it seems you are using powershell, which might not know where to look for python).

Then you can try :

First method (installing the dependencies manually):
`pip install youtube_dl`
`pip install pandas`
`pip install openpyxl`
and then
`python -m youtube_extract CHANNEL_URL` (in the youtube_extract folder)

Second method (it will install the dependencies automatically):
just `pip install youtube_extract` (if you uninstalled python 3.5 it should use the pip of 3.7 version)
and `youtube_extract CHANNEL_URL`

If you have a `pip` not found error it is because your terminal can't properly find the `pip` program in your computer. I don't have the exact same configuration and terminal than you so unfortunately I can't really help you on that side sorry.

**Comment by MakD** [comment]
I'm feeling such a noob. Uninstalled python, but forgot to remove it from the path. Now it's recognizing the correct pip. I have it running now. I will close this issue as soon as it completes. Thanks for this great and handy tool.

**Comment by MakD** [comment]
![Screenshot (127)](https://user-images.githubusercontent.com/8217200/78164289-2cc84f80-7467-11ea-8bf8-cdafe463c376.png)
 I have these recurring error message without any further context

**Comment by dbeley** [comment]
Does it work with another youtube channel (one with a small number of videos first)?
Try this one:
`youtube_extract https://www.youtube.com/channel/UCCCVgtMPRTC_adYMTQnfDmw/`
It works well for me (completion in 46 seconds).

But still it's strange that you have an empty error message. Can you try using the `--debug` flag to display more information?

 If you have random problem specially for channel with a high number of videos, it's unfortunately youtube that's not authorizing all requests. You would have to try on another computer or at another time.

**Comment by MakD** [comment]
It's a issue with my link I guess, owning with the huge amount of videos. But actually that's why I wanted this to perform so much... It runs perfect with the other link. I just hope it does the same with mine. Closing this, since it's not an issue with the tool.🙏
